# COMPORTEMENT ATTENDU :
#   POST body == 10 octets  → 201 Created
#   POST body == 11 octets  → 413 Request Entity Too Large
#   POST body == 0 octet    → 400 Bad Request
#
# CAS CRASH : off-by-one (> vs >=), size_t overflow sur Content-Length: -1

server {
    listen 127.0.0.1:8080;
    server_name test.com;
    root /home/romukena/Documents/webserv;
    index index.html;
    client_max_body_size 0;

    location / {
        allow_methods GET POST DELETE;
    }
    location /upload {
        allow_methods GET POST DELETE;
    }
}