server {
    listen localhost;
    server_name 127.0.0.1;

    root ./tests_www/static;
    index index.html;

    location / {
        root ./tests_www/static;
        allowed_methods GET;
        index index.html;
    }

    location /post_body {
        root ./tests_www/forms;
        allowed_methods POST;
        client_max_body_size 1000;
    }

    location /upload {
        root ./tests_www/upload;
        allowed_methods GET POST;
        client_max_body_size 1000000;
    }

    location /autoindex {
        root ./tests_www/autoindex;
        allowed_methods GET;
        autoindex on;
    }

    location /delete_test {
        root ./tests_www/forms;
        allowed_methods DELETE;
    }

    location /errors {
        root ./tests_www/errors;
        allowed_methods GET;
    }

    location /cgi-bin {
        root ./tests_www/cgi-bin;
        allowed_methods GET POST;
        cgi_extension .py /usr/bin/python3;
    }

    location /directory {
        root ./tests_www/cgi-bin;
        allowed_methods GET POST DELETE;
        index env.py;
        cgi_extension .py /usr/bin/python3;
    }
}